### ISSUE TITLE
追踪是如何实现的？

### ISSUE THREAD

**Issue by vc5** [seisman/blog.seisman.info#1]
请教下博主
追踪主题仓库和源码仓库是怎么实现的？

**Comment by seisman** [comment]
不是很理解你的意思。你是指博文里的
 ![selection_002](https://cloud.githubusercontent.com/assets/3974108/15530511/71f09d86-221a-11e6-8006-736c448ca0e8.png)
吗？如果是的话，基本是在这个commit里实现的： https://github.com/seisman/hexo-theme-next/commit/337334d5bb0f00c6034a29c247fda6665eb107a8

**Comment by vc5** [comment]
就是你所说的

> 本项目会追踪主题的 seisman 分支和博文的 master 分支。

点击这个source

![1](https://cloud.githubusercontent.com/assets/13097192/15534821/65a74f38-229d-11e6-8ca8-7023e329d1dc.png)
会跳转到post仓库
![2](https://cloud.githubusercontent.com/assets/13097192/15534851/87a2fec0-229d-11e6-857e-acd209686816.png)

**Comment by seisman** [comment]
这个是利用git的子模块实现的。从git 1.8.2开始，子模块可以用于追踪某一个具体的分支。

下面是个例子：

``` bash
$ mkdir my_project
$ cd my_project 
$ git init
Initialized empty Git repository in /home/seisman/Desktop/my_project/.git/
# 追踪posts的master分支
$ git submodule add -b master https://github.com/seisman/seisman.info.posts source
Cloning into 'source'...
remote: Counting objects: 507, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 507 (delta 6), reused 0 (delta 0), pack-reused 471
Receiving objects: 100% (507/507), 6.58 MiB | 1.72 MiB/s, done.
Resolving deltas: 100% (58/58), done.
# 追踪theme的seisman分支
$ git submodule add -b seisman https://github.com/seisman/hexo-theme-next/ themes/next
Cloning into 'themes/next'...
remote: Counting objects: 6137, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 6137 (delta 9), reused 0 (delta 0), pack-reused 6116
Receiving objects: 100% (6137/6137), 10.00 MiB | 2.03 MiB/s, done.
Resolving deltas: 100% (3305/3305), done.
```

**Comment by vc5** [comment]
Thank u,Dr. Tian.
